apiVersion: apps/v1
kind: Deployment
metadata:
  name: bbc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bbc
  template:
    metadata:
      labels:
        app: bbc
    spec:
      containers:
      - image: okteto.dev/bbc:latest
        name: bbc
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "e9af137f-3a11-4df6-9216-c8a37100ba91"
        - name: Vless_Path
          value: "/4wrgjyu"
        - name: Vmess_UUID
          value: "e9af137f-3a11-4df6-9216-c8a37100ba91"
        - name: Vmess_Path
          value: "/ui75u56ehtd"
        - name: Share_Path
          value: "/v2link"
